graph LR
    subgraph ワールド設置オブジェクト
        TC(コントローラー)
        TTB(切り替えボタン)
    end

    subgraph 動的に生成
        PTB(個人用タグボード)
    end

    PL(プレイヤー)

    PL -- "インタラクト" --> TTB

    TTB -- "タグ切り替え" --> TC


    TC -- "作成 (最初の切り替え時)" --> PTB
    TC -- "タグ切り替え" --> PTB

    PTB -- "追従" --> PL
